=== Ifkarsyah/openamq/management/core/etc/cml.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.openamq.org/schema/cml" xmlns="http://www.openamq.org/schema/cml">
    <xs:element name="cml">
        <xs:annotation>
            <xs:documentation>Defines a CML document as a schema or a...</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="schema" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="inspect" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
            <xs:attribute name="version" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="schema">
        <xs:annotation>
            <xs:documentation>Defines the CML schema as list of classes</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="class" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="version" type="xs:string" use="required"/>
            <xs:attribute name="status">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="ok"/>
                        <xs:enumeration value="not ok"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
        <xs:key name="classkey">
            <xs:selector xpath="class"/>
            <xs:field xpath="@name"/>
        </xs:key>
    </xs:element>
    <xs:element name="class">
        <xs:annotation>
            <xs:documentation>Defines a class which is a managable object</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="field" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required"/>
        </xs:complexType>
        <xs:unique name="uniqueFieldName">
            <xs:selector xpath="field"/>
            <xs:field xpath="@name"/>
        </xs:unique>
    </xs:element>
    <xs:element name="field">
        <xs:annotation>
            <xs:documentation>Defines a field within a class</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="type" use="optional" default="string">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="bool"/>
                        <xs:enumeration value="string"/>
                        <xs:enumeration value="int"/>
                        <xs:enumeration value="objref"/>
                    </xs:restriction>
                    </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="label" type="xs:string" use="optional"/>
            <xs:attribute name="repeat" type="xs:boolean" use="optional" default="false"/>
            <xs:attribute name="modify" type="xs:boolean" use="optional" default="false"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="inspect">
        <xs:annotation>
            <xs:documentation>A request to view the properties of an instance</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="field" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="object" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="object" type="xs:int" use="optional"/>
            <xs:attribute name="class" type="xs:string" use="optional"/>
            <xs:attribute name="status" use="optional">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="ok"/>
                        <xs:enumeration value="notfound"/>
                        <xs:enumeration value="noaccess"/>
                        <xs:enumeration value="invalid"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>

        </xs:complexType>
    </xs:element>
    <xs:element name="object">
        <xs:annotation>
            <xs:documentation>A reference to an object instance</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:attribute name="class" type="xs:string" use="required"/>
            <xs:attribute name="id" type="xs:int" use="required"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Ifkarsyah/openamq/management/core/etc/cml-exampleschema.xml
<?xml version="1.0" encoding="UTF-8"?>
<cml xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.openamq.org/schema/cml cml.xsd"
 xmlns="http://www.openamq.org/schema/cml"
 version="1.0">
<schema name = "openamq.org/kernel" version = "0.1" status = "ok">
   <class name = "broker">
      <field name = "started" label = "Date, time broker started" />
      <field name = "vhost" type = "objref" repeat = "1" />
   </class>
   <class name = "vhost">
      <field name = "name" label = "Virtual host path" />
      <field name = "exchange" type = "objref" repeat = "1" />
      <field name = "queue" type = "objref" repeat = "1" />
   </class>
   <class name = "exchange">
      <field name = "name" />
      <field name = "type" />
      <field name = "durable" label = "Durable exchange?" type = "bool" />
      <field name = "auto_delete" label = "Auto-deleted?" type = "bool" />
      <field name = "bindings" label = "Number of bindings" type = "int" />
   </class>
   <class name = "queue">
      <field name = "scope" />
      <field name = "name" />
      <field name = "enabled" label = "Queue accepts new messages?" modify = "1" />
      <field name = "durable" label = "Durable queue?" type = "bool" />
      <field name = "exclusive" label = "Exclusive to one connection?" type = "bool" />
      <field name = "auto_delete" label = "Auto-deleted?" type = "bool" />
      <field name = "consumers" label = "Number of consumers" type = "int" />
      <field name = "messages" label = "Number of messages" type = "int" />
   </class>
</schema>
</cml>
